print('==========FORM PENDATAAN SISWA UNTUK MENGISI ACARA INVOFEST==========')
print('==========HARAP MENGGUNAKAN HURUF KAPITAL UNTUK MENGISI FORM INI==========')
nama=str(input('MASUKAN NAMA ANDA :'))
nim=int(input("MASUKAN NIM :"))
fakultas=str(input("FAKULTAS :"))
harga=int(input('TOTAL YANG SUDAH ANDA BAYAR:'))
fakultas1=["TEKNIK INFORMATIKA","TEKNIK KOMPUTER"]
semester=str(input('SEMESTER:'))
semester1=["1","2","3"]
print('============KARTU MASUK UNTUK MENGIKUTI ACARA INI===========' if harga == 100000 and fakultas in fakultas1 and semester in semester1 else '============MOHON MAAF===========' )
print("NAMA =",nama)
print('NIM =',nim)
print('FAKULTAS =',fakultas)
print("SEMESTER =",semester)
status_pembayaran=("|SUDAH BAYAR|" if harga==100000 else "BELUM BAYAR")
print('STATUS PEMBAYARAN =',status_pembayaran)
print("==========SELAMAT ANDA DAPAT MENGIKUTI ACARA INI=========" if harga == 100000 and fakultas in fakultas1 and semester in semester1 else " =========MOHON MAAF ANDA TIDAK MEMENUHI SYARAT=========")
print('==========SILAHKAN CETAK FORM INI UNTUK MEMASUKI GATE ACARA=======' if harga == 100000 and fakultas in fakultas1 and semester in semester1 else "")
print('SILAHKAN ANDA MELUNASI PEMBAYARAN DULU' if harga < 100000 else '===========================' )
print("MOHON MAAF ANDA BUKAN DARI FAKULTAS YANG KAMI SYARATKAN" if fakultas not in fakultas1 else '===========================')
print("ANDA TERLALU SEPUH UNTUK MENGIKUTI ACARA INI" if semester not in semester1 else '===========================')